test tag step

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -12,7 +12,7 @@ env:
   REGISTRY_URL: satregistry.ehps.ncsu.edu
   PROJECT_NAME: clearance-tool
   REPO_NAME: clearance-ui
-  SLACK_UPDATES: true
+  SLACK_UPDATES: false
   SLACK_CHANNEL_ID: C053DS40S22
   E2E_REFRESH_TOKEN: ${{ secrets.E2E_REFRESH_TOKEN_ADMIN }}
   E2E_LIAISON_REFRESH_TOKEN: ${{ secrets.E2E_REFRESH_TOKEN_LIAISON }}
@@ -33,33 +33,33 @@ jobs:
           repository: SAT/sat-actions
           path: sat-actions
 
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 16
+      # - name: Setup Node
+      #   uses: actions/setup-node@v3
+      #   with:
+      #     node-version: 16
 
-      - name: Install Dependencies
-        run: npm ci
+      # - name: Install Dependencies
+      #   run: npm ci
 
-      - name: Run Tests
-        id: test
-        run: |
-          npx playwright install
-          npm run e2e
+      # - name: Run Tests
+      #   id: test
+      #   run: |
+      #     npx playwright install
+      #     npm run e2e
 
-      - name: Send Failure Message on Slack if Tests Fail
-        if: ${{ failure() }}
-        uses: ./sat-actions/slack-updates
-        with:
-          channel-id: ${{ github.event.inputs.slack-channel-id || env.SLACK_CHANNEL_ID }}
-          message: 'The tests for `clearance-ui` have failed.'
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
-          SLACK_UPDATES: ${{ github.event.inputs.slack-updates || env.SLACK_UPDATES }}
+      # - name: Send Failure Message on Slack if Tests Fail
+      #   if: ${{ failure() }}
+      #   uses: ./sat-actions/slack-updates
+      #   with:
+      #     channel-id: ${{ github.event.inputs.slack-channel-id || env.SLACK_CHANNEL_ID }}
+      #     message: 'The tests for `clearance-ui` have failed.'
+      #   env:
+      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+      #     SLACK_UPDATES: ${{ github.event.inputs.slack-updates || env.SLACK_UPDATES }}
 
-      - name: End the Job if the Tests Fail
-        if: ${{ failure() }}
-        run: exit 1
+      # - name: End the Job if the Tests Fail
+      #   if: ${{ failure() }}
+      #   run: exit 1
 
       - name: Docker Login
         uses: ./sat-actions/docker-login
@@ -77,12 +77,18 @@ jobs:
           tags: |
             type=raw,value={{branch}}.{{sha}}.{{date 'YYYY-MM-DD.HHmm'}}Z
 
-      - name: Update Docker Image
-        id: image-update
-        uses: ./sat-actions/update-image
-        with:
-          image-tag: ${{ steps.meta.outputs.tags }}
-          dockerfile: ./Dockerfile
+      # - name: Update Docker Image
+      #   id: image-update
+      #   uses: ./sat-actions/update-image
+      #   with:
+      #     image-tag: ${{ steps.meta.outputs.tags }}
+      #     dockerfile: ./Dockerfile
+
+      - name: Modify Tag String
+        id: image-tag-string
+        run: |
+          tag_strings="${{ split(steps.meta.outputs.tags), ':' }}"
+          echo "tag=tag_strings[1]" >> $TAG_NAME
 
       - name: Send Failure Message on Slack if Image Upload Fails
         if: ${{ failure() && steps.image-update.conclusion == 'failure' }}
